version: "3"

services:
  nginx:
    build: .
    ports:
     - "80:80"
     - "443:443"
    env_file:
     - env/nginx.env
    volumes:
     - "nginx_tls_cert:/etc/ssl:rw"
     - "nginx_acme_challenge:/var/www/.well-known/acme-challenge:ro"
     - "nginx_logs:/var/log/nginx:rw"

  node:
    build: test/node
    ports:
     - "3000:3000"

#  crontab:
#    build: test/crontab
#    volumes:
#    # docker
#     - "/var/run/docker.sock:/var/run/docker.sock:ro"
#     - "./env:/opt/env:ro"

volumes:
  nginx_tls_cert:
  nginx_acme_challenge:
  nginx_logs: